services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: transport
      POSTGRES_USER: transport
      POSTGRES_PASSWORD: transport
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
